### ISSUE TITLE
Sign-in problem

### ISSUE THREAD

**Issue by calllka21** [mzmaili/Get-AzureADUsersLastSignIn#3]
Hello,
I have used this script back in september and october and it worked very well.  When I tried to use it now, I get the following error.  I tried on 2 different o365 tenants with same results.

=============================================================
Sorry, but we’re having trouble signing you in.

AADSTS65002: Consent between first party application '1950a258-227b-4e31-a9cf-717495945fc2' and first party resource '00000003-0000-0000-c000-000000000000' must be configured via preauthorization - applications owned and operated by Microsoft must get approval from the API owner before requesting tokens for that API. 
=============================================================

**Comment by mzmaili** [comment]
Thanks for your feedback. This issue has been fixed now. Thanks!

**Comment by calllka21** [comment]
Thank you, it's working now.
